### ISSUE TITLE
Litematica Lag

### ISSUE THREAD

**Issue by SirPotato42** [caoimhebyrne/compact-chat#27]
When pasting in a large schematic using litematica, it floods chat with messages like the ones in the attached image.
This causes the client to lag a lot as they pile up, bringing fps down to less than 1.
I have tested this on several computers, with/without optimization mods, and with several different schematics of varying sizes, all results point to compact chat being the issue

![issue](https://github.com/caoimhebyrne/compact-chat/assets/84108315/a1282cbc-35bc-4502-9b59-81a37a6edc3f)

I think as the number of messages per second increases quickly, the mod has trouble checking the newest message against all other messages, so this may not just be an issue with litematica, but rather an optimization issue with the mod in general.

**Comment by caoimhebyrne** [comment]
Hi, thanks for the report. I'll take a look at this and see if there's anything we can do to resolve this! Just to confirm, this only occurs with Compact Chat installed?

**Comment by SirPotato42** [comment]
Yes, that is correct.

This issue only occurs with Compact Chat Installed. It is easily reproduced
by pasting in a litematic, with the gamerule sendCommandfeedback = true
(I've found setting it false alleviates the issue).

Without litematica, it can also be reproduced by having several repeating
command blocks spam send messages in the chat.

Thank you for looking into this.

**Comment by caoimhebyrne** [comment]
I will try to fix this over the Christmas break... it looks like I have some optimising to do!

**Comment by caoimhebyrne** [comment]
This has been fixed in 2.0.4.

[Modrinth](https://modrinth.com/mod/compact-chat/version/WTGMj87L) - [GitHub Releases](https://github.com/caoimhebyrne/compact-chat/releases/tag/2.0.4)
