### ISSUE TITLE
Crash on join to server

### ISSUE THREAD

**Issue by Krzychu4u** [caoimhebyrne/compact-chat#28]
When I join to server my game crash. It's start crashing when i add compact chat 2.0.2

My mods folder:
compact-chat-2.0.2
fabric-api-0.91.1+1.20.3
litematica-fabric-1.20.4-0.17.0
malilib-fabric-1.20.4-0.18.0
sodium-fabric-mc.1.20.3-0.5.5
cloth-config-13.0.121-fabric

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/minecraft/class_2585
Minecraft Luncher Exit Code: -1

[latest.log](https://github.com/caoimhebyrne/compact-chat/files/13819544/latest.log) - https://pastebin.com/5yiTjE10

[crash-2024-01-03_14.29.46-client.txt](https://github.com/caoimhebyrne/compact-chat/files/13819542/crash-2024-01-03_14.29.46-client.txt) - https://pastebin.com/8MsN1zk0

**Comment by caoimhebyrne** [comment]
You are using Minecraft 1.20.3, which is unsupported.

If you want to use 1.20 or 1.20.1, use [Compact Chat v2.0.2](https://modrinth.com/mod/compact-chat/version/2.0.2)
If you want to use 1.20.4 or higher, use [Compact Chat v2.0.3](https://modrinth.com/mod/compact-chat/version/2.0.3).

**Comment by Krzychu4u** [comment]
Will there ever be support for 1.20.3?

**Comment by caoimhebyrne** [comment]
1.20.4 and 1.20.3 are very similar, so no. I'd recommend you just use the latest version considering it fixes a data-loss issue introduced in 1.20.3, @Krzychu4u.
