### ISSUE TITLE
100+ Messages

### ISSUE THREAD

**Issue by SirPotato42** [caoimhebyrne/compact-chat#30]
It seems that since issue #27, although the lag has been fixed, whenever you do exceed the 100 message limit, any subsequent chats that contain the same text are not compacted into the (100+) instance of the message, but rather sent separately with a (100+) counter next to them.

Therefore, even though exactly 101 messages could have been sent all with the same text, there will be 2 messages in the chat, both containing the text and the (100+) counter next to them, implying at least 200 messages have been sent. This continues on for each subsequent message.

![image](https://github.com/caoimhebyrne/compact-chat/assets/84108315/76cda8bb-2913-4b0e-8fbb-416a7e075a41)

It seems that the 100 counter limit was implemented to resolve the lag, which I am very grateful for, but it would also be nice to have a setting, perhaps in modmenu, to customize this limit.

**Comment by caoimhebyrne** [comment]
Ouch, not sure how I messed that up. Thanks, I'll fix that.

**Comment by caoimhebyrne** [comment]
Fixed in v2.1.0.

[GitHub Releases](https://github.com/caoimhebyrne/compact-chat/releases/tag/2.1.0) - [Modrinth](https://modrinth.com/mod/compact-chat)
