### ISSUE TITLE
Messages don't compact

### ISSUE THREAD

**Issue by MathiasDPX** [caoimhebyrne/compact-chat#33]
![image](https://github.com/user-attachments/assets/59b441d8-38f9-419e-806f-0bcf42371384)

### Mods:
![image](https://github.com/user-attachments/assets/56b246e0-e794-4b2f-806b-d94cbc1c0ea8)

**Comment by caoimhebyrne** [comment]
you're using xray

**Comment by MathiasDPX** [comment]
> you're using xray

It's an xray alert, when someone broke a diamond, I got ping
