### ISSUE TITLE
1.21.2 / 1.21.3 support? :D

### ISSUE THREAD

**Issue by Nilsson321** [caoimhebyrne/compact-chat#36]

**Comment by caoimhebyrne** [comment]
Coming soon!

**Comment by Nilsson321** [comment]
ETA?

**Comment by caoimhebyrne** [comment]
It seems compact chat already supports 1.21.3, I just need to update modrinth to reflect that.
<img width="966" alt="image" src="https://github.com/user-attachments/assets/6c197ab2-64f5-4954-bc22-a8d60d534034">
